ballerina-platform/module-ballerina-jwt

jwt-ballerina/build.gradle
Fixes https://github.com/ballerina-platform/module-ballerina-jwt/issues/4
- Ballerina 2.0.0-SNAPSHOT
- Java 8
- macOS
=> Pack balos along with the final pack

jwt-ballerina/src/jwt/jwt_validator.bal
=> Return error when JWK request failed

jwt-ballerina/src/jwt/inbound_jwt_auth_provider.bal, jwt-ballerina/src/jwt/jwt_errors.bal, jwt-ballerina/src/jwt/jwt_validator.bal, jwt-ballerina/src/jwt/outbound_jwt_auth_provider.bal, jwt-ballerina/src/jwt/tests/integration-tests/authn_with_expired_certificate_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/authn_with_multiple_handlers_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/authz_cache_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/jwk_signature_validation_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/token_propagation_tests.bal, jwt-ballerina/src/jwt/tests/mock-servers/authn_with_expired_certificate.bal, jwt-ballerina/src/jwt/tests/mock-servers/authn_with_multiple_handlers.bal, jwt-ballerina/src/jwt/tests/mock-servers/authz_with_cache.bal, jwt-ballerina/src/jwt/tests/mock-servers/jwt_signature_validation_with_jwk.bal, jwt-ballerina/src/jwt/tests/mock-servers/token_propagation_basic_auth.bal, jwt-ballerina/src/jwt/tests/mock-servers/token_propagation_disabled.bal, jwt-ballerina/src/jwt/tests/mock-servers/token_propagation_jwt.bal, jwt-ballerina/src/jwt/tests/mock-servers/token_propagation_jwt_reissuing.bal, jwt-ballerina/src/jwt/tests/mock-servers/token_propagation_jwt_reissuing_negative.bal, jwt-ballerina/src/jwt/tests/unit-tests/jwt-auth-provider-test.bal, jwt-ballerina/src/jwt/tests/unit-tests/jwt-issuer-and-validator-test.bal
$subject
Mainly resolve error related changes.
Ballerina-2.0.0-SNAPSHOT
=> Sync new changes with the balleirna-lang

build.gradle, gradle.properties, jwt-ballerina/Ballerina.toml, jwt-ballerina/build.gradle
$subject
https://github.com/ballerina-platform/ballerina-lang/issues/23559
=> Added configuration to package and release

.github/workflows/daily-build.yml
=> Enable daily build

jwt-ballerina/src/jwt/inbound_jwt_auth_provider.bal, jwt-ballerina/src/jwt/jwt_validator.bal
This PR add support to preload JWKs when initializing the inbound JWT provider. This will avoid the latency introduced due to HTTP call when validating the signature using JWK.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/24649
=> Add support to load JWKs when initializing

jwt-ballerina/src/jwt/inbound_jwt_auth_provider.bal, jwt-ballerina/src/jwt/outbound_jwt_auth_provider.bal
Update JWT module for refactoring of `ballerina/runtime` module with PR [1]
[1] https://github.com/ballerina-platform/ballerina-lang/pull/24629
=> Update JWT module for refactoring of `ballerina/runtime` module

gradle.properties
=> Upgrade module version

build.gradle
=> Update Nexus URL for release

build.gradle, gradle.properties, jwt-ballerina/build.gradle
=> Upgrade ballerina version & fix license headers

gradle.properties
=> Upgrade versions

jwt-ballerina/build.gradle, jwt-ballerina/src/jwt/tests/integration-tests/authn_with_expired_certificate_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/authn_with_multiple_handlers_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/authz_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/signature_validation_tests.bal, jwt-ballerina/src/jwt/tests/integration-tests/token_propagation_tests.bal, jwt-ballerina/src/jwt/tests/mock-servers/jwk-mock-server.bal, jwt-ballerina/src/jwt/tests/unit-tests/jwt-auth-provider-test.bal, jwt-ballerina/src/jwt/tests/unit-tests/jwt-issuer-and-validator-test.bal
=> Add note of dummy credentials

jwt-ballerina/src/jwt/inbound_jwt_auth_provider.bal, jwt-ballerina/src/jwt/outbound_jwt_auth_provider.bal
=> Fix jwt module for object syntax change

.github/workflows/pull-request.yml, jwt-ballerina/src/jwt/jwt_validator.bal
=> Update GitHub actions

.github/workflows/publish-release.yml, build.gradle, jwt-ballerina/build.gradle
=> Update GitHub release workflow

jwt-ballerina/src/jwt/inbound_jwt_auth_provider.bal, jwt-ballerina/src/jwt/jwt_errors.bal, jwt-ballerina/src/jwt/jwt_issuer.bal, jwt-ballerina/src/jwt/jwt_validator.bal, jwt-ballerina/src/jwt/outbound_jwt_auth_provider.bal
$subject
Fixes: https://github.com/ballerina-platform/module-ballerina-jwt/issues/42
=> Update jwt module with isolated functions

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, README.md
=> Migrate to JDK11

jwt-ballerina/src/jwt/inbound_jwt_auth_provider.bal, jwt-ballerina/src/jwt/jwt_validator.bal
$subject
https://docs.google.com/document/d/161cAqT_AbH4b95k6itdRrgqWbSSC14FGuMNo6Blbrw8/edit
=> Fix for HTTP client API changes

jwt-ballerina/build.gradle
=> Enable copying of dependency caches and doc generation

build.gradle, jwt-ballerina/build.gradle, jwt-ballerina/tests/jwt_auth_provider_test.bal, jwt-ballerina/tests/jwt_issuer_and_validator_test.bal
=> Refactor gradle configurations

jwt-ballerina/jwt_errors.bal, jwt-ballerina/jwt_validator.bal
=> Update for log API changes

jwt-ballerina/init.bal, jwt-native/src/main/java/org/ballerinalang/stdlib/jwt/JwksClient.java, jwt-native/src/main/java/org/ballerinalang/stdlib/jwt/ModuleUtils.java
=> Replace hard coded native package version

jwt-ballerina/client_self_signed_jwt_auth_provider.bal, jwt-ballerina/jwt_commons.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/tests/jwt_issuer_and_validator_test.bal
=> Refactor custom claims of JWT payload

jwt-ballerina/client_self_signed_jwt_auth_provider.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/tests/jwt_issuer_and_validator_test.bal
=> Improve API of self signed JWT issuer

jwt-ballerina/client_self_signed_jwt_auth_provider.bal, jwt-ballerina/jwt_errors.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal
=> Fix for syntax changes related to errors

jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal
=> Refactor JWT related cache configurations and signature validation

build.gradle, gradle.properties, jwt-ballerina/Ballerina.toml, jwt-ballerina/build.gradle, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal, jwt-ballerina/tests/jwt_issuer_and_validator_test.bal
=> Replace usages of stringutils APIs

jwt-ballerina/jwt_commons.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal
=> Add support of optional fields of JWT header

jwt-ballerina/build.gradle
=> Update ballerina command to bal command

jwt-ballerina/Package.md
=> Update package md files

jwt-ballerina/init.bal, jwt-ballerina/jwt_validator.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

jwt-ballerina/Ballerina.toml, jwt-ballerina/Dependencies.toml, jwt-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

README.md, jwt-ballerina/client_self_signed_jwt_auth_provider.bal, jwt-ballerina/jwt_commons.bal, jwt-ballerina/jwt_errors.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal
=> Update ballerina documentations

jwt-ballerina/build.gradle
=> Revert dependency toml file after build

build-config/checkstyle/build.gradle, build.gradle, gradle.properties, jwt-native/build.gradle, jwt-native/src/main/java/org/ballerinalang/stdlib/jwt/JwksClient.java
=> Enable checkstyle and spotbugs

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, jwt-ballerina/build.gradle
=> Publish code coverage exec file as a maven artifact

jwt-ballerina/build.gradle
=> Refactor build task order

jwt-ballerina/build.gradle
=> Avoid running tests twice when publishing

jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal
=> Refactor JWT validating API

jwt-ballerina/tests/jwt_issuer_and_validator_test.bal
$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Refactor JWT issue/validate test cases

jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal
$subject
Related to
https://github.com/ballerina-platform/module-ballerina-crypto/pull/61
https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Update crypto API changes

README.md, jwt-ballerina/Package.md
=> Update docs for swan-lake URL change

.github/workflows/publish-release.yml, build.gradle, gradle.properties, jwt-ballerina/build.gradle
- Subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/957
- Bump the next version to a minor alpha version
- Improve the build scripts and actions to publish the artifacts to the Ballerina central during a release
=> Enable publishing to Ballerina Central during release

jwt-ballerina/client_self_signed_jwt_auth_provider.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal
=> Refactor error messages

build.gradle, jwt-ballerina/build.gradle
=> Re-order build tasks to publish to ballerina central

jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal, jwt-native/src/main/java/org/ballerinalang/stdlib/jwt/JwksClient.java
$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Refactor error messages and debug logs

jwt-ballerina/jwt_validator.bal
=> Fix for removal of error type from anydata

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, jwt-ballerina/build.gradle
=> Remove publishing exec artifacts and archiving test json

jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/tests/jwt_issuer_and_validator_test.bal
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/967
=> Update fields representing time-units with the convention

jwt-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

jwt-ballerina/Package.md
$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1376
=> Update Package.md for BBE update

jwt-ballerina/jwt_errors.bal, jwt-ballerina/jwt_validator.bal, jwt-native/src/main/java/org/ballerinalang/stdlib/jwt/JwtConstants.java
=> Update error types and log API

gradle.properties, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal
=> Update for Time API changes

build.gradle, gradle.properties, jwt-ballerina/Dependencies.toml, jwt-ballerina/build.gradle, jwt-ballerina/jwt_issuer.bal
Add the `jti` claim of the `jwt:Payload` as a user input of `jwt:IssuerConfig`
=> Add `jti` claim as a user input

jwt-ballerina/jwt_validator.bal
=> Fix nbf/exp claim validation

jwt-ballerina/client_self_signed_jwt_auth_provider.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal, jwt-ballerina/tests/jwt_issuer_and_validator_test.bal
This PR remove the `checkpanic` keyword usages for type narrowing.
=> Remove usages of checkpanic for type narrowing

changelog.md, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal, jwt-ballerina/tests/jwt_issuer_and_validator_test.bal, jwt-native/src/main/java/org/ballerinalang/stdlib/jwt/JwksClient.java
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1242
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Improve error messages and log messages

build.gradle, jwt-ballerina/build.gradle
=> Strip stdlib dependency version

jwt-ballerina/build.gradle
=> Fix publishing workfow

jwt-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

.github/workflows/pull-request.yml, jwt-ballerina/build.gradle
=> Skip Docker based tests in Windows OS

README.md, jwt-ballerina/Module.md, jwt-ballerina/Package.md, jwt-ballerina/client_self_signed_jwt_auth_provider.bal, jwt-ballerina/jwt_errors.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/listener_jwt_auth_provider.bal, jwt-ballerina/tests/test_utils.bal
$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Improve the API documentation and markdown files

jwt-ballerina/build.gradle
$subject
Related to https://github.com/ballerina-platform/module-ballerina-jwt/pull/228
=> Fix a bug in gradle task order

jwt-ballerina/Module.md, jwt-ballerina/jwt_commons.bal, jwt-ballerina/jwt_validator.bal
=> Improve API docs

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, gradle.properties
This is related to https://github.com/ballerina-platform/ballerina-release/issues/547
=> Improve GitHub action workflow scripts

jwt-ballerina/Package.md
This is a part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1462
=> Update Package.md links into HTML format

changelog.md, jwt-ballerina/jwt_commons.bal, jwt-ballerina/jwt_issuer.bal, jwt-ballerina/jwt_validator.bal, jwt-ballerina/tests/jwt_issuer_test.bal, jwt-ballerina/tests/jwt_validator_test.bal, jwt-ballerina/tests/test_utils.bal
This PR improves the existing JWT validation configuration support further.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1240
=> Improve JWT validator configurations support

ballerina/tests/test_utils.bal
=> Fix build failure due to JWT expiry

load-tests/order_management_service/src/Cloud.toml
$subject related to https://github.com/ballerina-platform/module-ballerina-jwt/pull/402
=> Fix Docker image name

.github/workflows/create-summary-pr.yml, .github/workflows/trigger-load-tests.yml
=> Refactor namings of GitHub actions

examples/order-management-service/README.md, examples/order-management-service/order_service/order_service.bal
=> Fix examples for SL-Beta4 changes

examples/order-management-service/order_service/order_service.bal
$subject related to https://github.com/ballerina-platform/module-ballerina-jwt/pull/416
=> Fix imports

ballerina/client_self_signed_jwt_auth_provider.bal, ballerina/jwt_errors.bal, ballerina/jwt_issuer.bal, ballerina/jwt_validator.bal, ballerina/listener_jwt_auth_provider.bal, ballerina/tests/client_self_signed_jwt_auth_provider_test.bal, ballerina/tests/jwt_issuer_test.bal, ballerina/tests/jwt_validator_test.bal, ballerina/tests/listener_jwt_auth_provider_test.bal, ballerina/tests/test_utils.bal, examples/order-management-service/order_service/order_service.bal
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2200
=> Refactor code base

.github/workflows/pull-request.yml, ballerina/tests/jwt_issuer_test.bal, ballerina/tests/jwt_validator_test.bal
$subject fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2195
=> Improve unit tests with negative tests

README.md, ballerina/Module.md, ballerina/Package.md
=> Update sample code section markdown files

examples/order-management-service/README.md
=> Fix a term used in examples

ballerina/jwt_errors.bal, ballerina/listener_jwt_auth_provider.bal, load-tests/order_management_service/src/sts.bal
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3026
N/A
=> Convert error logs to debug logs

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
> $subject
Related to [#3128](https://github.com/ballerina-platform/ballerina-standard-library/issues/3128)
N/A
=> Migrate JWT module to Ballerina Update 2

docs/spec/spec.md
=> Fix inconsistencies in JWT spec

README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/Package.md, build-config/resources/Ballerina.toml, changelog.md, docs/spec/spec.md, gradle.properties
> $subject
Part of [#3463](https://github.com/ballerina-platform/ballerina-standard-library/issues/3463)
N/A
=> Update ballerina-lang and ballerina distribution version

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/build.gradle
> $subject
Part of: [#4021](https://github.com/ballerina-platform/ballerina-standard-library/issues/4021)
N/A
=> Optimize build script to skip docker tasks when using the `-x test` flag

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update dependency versions for 2201.5.0 release

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/jwt_validator.bal, ballerina/listener_jwt_auth_provider.bal, ballerina/tests/jwt_issuer_test.bal, build.gradle, gradle.properties
=> Remove Regex Package Usages

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Update std lib versions

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, .github/workflows/update_specs.yml, README.md, ballerina/Ballerina.toml, build-config/checkstyle/build.gradle, build-config/resources/Ballerina.toml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, settings.gradle
=> Migrate to Java 17

.github/workflows/build-with-bal-test-graalvm.yml
=> Change lang tag for graalvm build

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Bump to the Next Minor Version and Update the Distribution

docs/spec/spec.md
=> Update spec meta-data

docs/spec/spec.md
Reverts ballerina-platform/module-ballerina-jwt#1232
=> Revert "Update spec meta-data"

ballerina/Dependencies.toml, gradle.properties
=> Update depedency versions for U10

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Revert JWT major version bump and update to next minor version

.github/workflows/central-publish.yml
=> Fix workflow template path
